[package]
name = "matrix-terminal"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.26"
egui = "0.26"
tokio = { version = "1.0", features = ["full"] }
chrono = "0.4"
rand = "0.8"
sysinfo = "0.30"
log = "0.4"
env_logger = "0.11"
log4rs = "1.2"

[build-dependencies]
winres = "0.1"
